#! /bin/sh

sxhkd &
[ -x ~/.config/polybar/launch.sh ] && ~/.config/polybar/launch.sh &
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10
bspc config focused_border_color \#3c3836
bspc config normal_border_color \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a ulauncher focus=on
bspc rule -a polybar border=off manage=off
bspc rule -a firefox desktop='^1'
